routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', App\Http\Controllers\Auth\AuthRedirectorController::class);

Route::name('admin.')->prefix('admin')->middleware(['isAdmin', 'auth'])->group(function () {
    Route::get('/dashboard', \App\Http\Controllers\Web\Admin\DashboardController::class)->name('dashboard');

    /** Notifications */
        Route::get('/notifications/{notification}/read', '\App\Http\Controllers\Web\Admin\Notifications\NotificationController@read')->name('notifications.read');
        Route::get('/notifications/readAll', '\App\Http\Controllers\Web\Admin\Notifications\NotificationController@readAll')->name('notifications.readAll');

    /** Models */
        Route::resource('users', \App\Http\Controllers\Web\Admin\Users\UserController::class, ['except' => ['show']]);
        Route::resource('permits', \App\Http\Controllers\Web\Admin\Permits\PermitController::class, ['except' => ['show']]);
        Route::resource('reports', \App\Http\Controllers\Web\Admin\Reports\ReportController::class);
});

Route::name('bitboss.')->prefix('bitboss')->middleware(['isBitboss', 'auth'])->group(function () {
    Route::get('/home', \App\Http\Controllers\Web\Bitboss\HomeController::class)->name('home');

    /** Notifications */
        Route::get('/notifications/{notification}/read', '\App\Http\Controllers\Web\Bitboss\Notifications\NotificationController@read')->name('notifications.read');
        Route::get('/notifications/readAll', '\App\Http\Controllers\Web\Admin\Bitboss\NotificationController@readAll')->name('notifications.readAll');

    /** Models */
        Route::resource('permits', \App\Http\Controllers\Web\Bitboss\Permits\PermitController::class);
        Route::resource('reports', \App\Http\Controllers\Web\Bitboss\Reports\ReportController::class);

    /** Files */
        Route::post('uploads', '\App\Http\Controllers\Web\Bitboss\Reports\UploadController@upload')->name('upload');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->first_name . " " . $this->last_name;
    }

    /**
     * @return mixed
     */
    public function getRoleAttribute()
    {
        if (!empty($this->roles)) {
            return $this->roles->first();
        }
    }
}

app/Http/Controllers/Web/Admin/Users/UserController.php
<?php

namespace App\Http\Controllers\Web\Admin\Users;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Validators\Admin\Users\UsersValidator;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class UserController extends Controller
{

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $this->authorize('admin.users.show');

        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        $this->authorize('admin.users.update');

        return view('admin.users.create');
    }

    /**
     * @param Request $request
     * @param UsersValidator $validator
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request, UsersValidator $validator)
    {
        $this->authorize('admin.users.update');

        $validator->validate_store($request);

        $user = User::create(
            array_merge($request->user, [
                'password' => bcrypt(Str::random(10)),
            ]));

        $user->assignRole('Bitboss');

        //Invio email

        return redirect(route('admin.users.index'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(User $user)
    {
        $this->authorize('admin.users.update');

        return view('admin.users.edit', compact('user'));
    }

    /**
     * @param Request $request
     * @param User $user
     * @param UsersValidator $validator
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, User $user, UsersValidator $validator)
    {
        $this->authorize('admin.users.update');

        $validator->validate_update($request);

        $user->update($request->user);

        if ($request->password)
            $user->update(['password' => bcrypt($request->password['password'])]);

        return redirect(route('admin.users.index'));
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.app', ['title'=>__("Utenti")])

@section('content')

    <form method="POST" action="{{route('admin.users.store')}}">
        {!! csrf_field() !!}

            <div>
                <div class="content container-fluid">
                    <div class="page-header m-0">
                        <div class="row align-items-end">
                            <div class="col-sm mb-2 mb-sm-0">
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb breadcrumb-no-gutter">
                                        <li class="breadcrumb-item"><a class="breadcrumb-link" href="{{route('admin.users.index')}}:;">Utenti</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">Nuovo utente</li>
                                    </ol>
                                </nav>

                                <h1 class="page-header-title">Nuovo utente</h1>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">
                                Salva
                            </button>
                        </div>
                    </div>
                </div>
                </div>



                <div class="mt-3">
                    @include('admin.partials._errors_list')
                </div>

                <div class="tab-content pt-4">

                <div class="tab-pane show active" id="details" role="tabpanel">
                    @include('admin.users.partials.form')
                </div>
            </div>

    </form>

@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.app', ['title'=>__($user->fullName)])

@section('content')

    <form action="{{route('admin.users.update', $user)}}" method="post">
        {!! csrf_field() !!}
        {{ method_field('PUT') }}
        <div>
            <div class="content container-fluid">
                <div class="page-header m-0">
                    <div class="row align-items-end">
                        <div class="col-sm mb-2 mb-sm-0">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb breadcrumb-no-gutter">
                                    <li class="breadcrumb-item"><a class="breadcrumb-link" href="{{route('admin.users.index')}}:;">Utenti</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">{{$user->fullName}}</li>
                                </ol>
                            </nav>

                            <h1 class="page-header-title">{{$user->fullName}}</h1>
                        </div>
                        <button type="submit" class="btn btn-primary pull-right">
                            Salva
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="mt-3">
            @include('admin.partials._errors_list')
        </div>

        <div class="tab-content pt-4">
            <div class="tab-pane show active" id="details" role="tabpanel">
                @include('admin.users.partials.form')
            </div>
        </div>
    </form>

@endsection

resources/views/admin/users/index.blade.php
@extends('admin.app', ['title'=>__("Utenti")])

@section('content')

    <div class="mb-7">
        <div class="content container-fluid">
            <!-- Page Header -->
            <div class="page-header">
                <div class="row align-items-end">
                    <div class="col-sm mb-2 mb-sm-0">
                        {{--<nav aria-label="breadcrumb">
                            <ol class="breadcrumb breadcrumb-no-gutter">
                                <li class="breadcrumb-item"><a class="breadcrumb-link" href="javascript:;">Pages</a></li>
                                <li class="breadcrumb-item"><a class="breadcrumb-link" href="javascript:;">Users</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Overview</li>
                            </ol>
                        </nav>--}}

                        <h1 class="page-header-title">Utenti</h1>
                    </div>

                    <div class="col-sm-auto">
                        <a class="btn btn-primary" href="{{route('admin.users.create')}}">
                            <i class="tio-user-add mr-1"></i> Nuovo
                        </a>
                    </div>
                </div>
                <!-- End Row -->
            </div>
            <!-- End Page Header -->

            <div class="card">
                <div class="card-body">
                    <div class="table-responsive-sm">
                        <table class="table table-striped table-centered mb-0">
                            <thead class="thead-light">
                            <tr>
                                <th>Nome e cognome</th>
                                <th>Email</th>
                                <th>Ruolo</th>
                                <th>Azioni</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($users as $user)
                                <tr role="row" class="odd">
                                    <td class="table-column-pl-0">
                                        {{--<div class="avatar avatar-circle">
                                            <img class="avatar-img" src="./assets/img/160x160/img10.jpg" alt="Image Description">
                                        </div>--}}
                                        <div class="ml-3">
                                            <a class="d-flex align-items-center" href="{{route('admin.users.edit', $user)}}">
                                                <div class="avatar avatar-sm avatar-soft-primary avatar-circle mr-2">
                                                    <span class="avatar-initials">{{$user->first_name[0]}}</span>
                                                </div>
                                                <div class="ml-3">
                                                    <span class="d-block h5 text-hover-primary mb-0">{{$user->fullName}}</span>
                                                </div>
                                            </a>
                                        </div>
                                    </td>
                                    <td>
                                        <span class="d-block text-hover-primary mb-0">{{$user->email}}</span>
                                    </td>
                                    <td>
                                        <span class="d-block mb-0">@lang('users.roles.' . $user->role->name)</span>
                                    </td>
                                    <td>
                                        <a class="btn btn-xs btn-white" href="{{route('admin.users.edit', $user)}}">
                                            <i class="tio-edit"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            </div>
        </div>
    </div>

@endsection