routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', App\Http\Controllers\Auth\AuthRedirectorController::class);

Route::name('admin.')->prefix('admin')->middleware(['isAdmin', 'auth'])->group(function () {
    Route::get('/dashboard', \App\Http\Controllers\Web\Admin\DashboardController::class)->name('dashboard');

    /** Notifications */
        Route::get('/notifications/{notification}/read', '\App\Http\Controllers\Web\Admin\Notifications\NotificationController@read')->name('notifications.read');
        Route::get('/notifications/readAll', '\App\Http\Controllers\Web\Admin\Notifications\NotificationController@readAll')->name('notifications.readAll');

    /** Models */
        Route::resource('users', \App\Http\Controllers\Web\Admin\Users\UserController::class, ['except' => ['show']]);
        Route::resource('permits', \App\Http\Controllers\Web\Admin\Permits\PermitController::class, ['except' => ['show']]);
        Route::resource('reports', \App\Http\Controllers\Web\Admin\Reports\ReportController::class);
});

Route::name('bitboss.')->prefix('bitboss')->middleware(['isBitboss', 'auth'])->group(function () {
    Route::get('/home', \App\Http\Controllers\Web\Bitboss\HomeController::class)->name('home');

    /** Notifications */
        Route::get('/notifications/{notification}/read', '\App\Http\Controllers\Web\Bitboss\Notifications\NotificationController@read')->name('notifications.read');
        Route::get('/notifications/readAll', '\App\Http\Controllers\Web\Admin\Bitboss\NotificationController@readAll')->name('notifications.readAll');

    /** Models */
        Route::resource('permits', \App\Http\Controllers\Web\Bitboss\Permits\PermitController::class);
        Route::resource('reports', \App\Http\Controllers\Web\Bitboss\Reports\ReportController::class);

    /** Files */
        Route::post('uploads', '\App\Http\Controllers\Web\Bitboss\Reports\UploadController@upload')->name('upload');
});

app/Models/Reports/Report.php
<?php

namespace App\Models\Reports;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class Report extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * @return string
     */
    public function reported()
    {
        return $this->belongsTo(User::class, 'reported_id');
    }
}

app/Http/Controllers/Web/Admin/Reports/ReportController.php
<?php

namespace App\Http\Controllers\Web\Admin\Reports;

use App\Http\Controllers\Controller;
use App\Models\Permits\Permit;
use App\Models\Reports\Report;
use App\Models\User;

class ReportController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $this->authorize('admin.reports.show');

        $reports = Report::all();
        $users = User::all();

        return view('admin.reports.index', compact('reports', 'users'));
    }
}

app/Http/Controllers/Web/Bitboss/HomeController.php
<?php

namespace App\Http\Controllers\Web\Bitboss;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * DashboardController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function __invoke()
    {
        return view('bitboss.home.home', ['user' => Auth::user()]);
    }
}

app/Http/Controllers/Web/Bitboss/Notifications/NotificationController.php
<?php

namespace App\Http\Controllers\Web\Bitboss\Notifications;

use App\Http\Controllers\Controller;
use Illuminate\Notifications\DatabaseNotification;
use Illuminate\Notifications\Notification;
use Illuminate\Support\Facades\Auth;

class NotificationController extends Controller
{

    /**
     * @param DatabaseNotification $notification
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function read(DatabaseNotification $notification)
    {
        if (!$notification->read_at) {
            $notification->markAsRead();
        }

        return redirect($notification->data['redirect']);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function readAll()
    {
        foreach (Auth::user()->notifications as $notification) {
            if (!$notification->read_at) {
                $notification->markAsRead();
            }
        }

        return back();
    }
}

app/Http/Controllers/Web/Bitboss/Permits/PermitController.php
<?php

namespace App\Http\Controllers\Web\Bitboss\Permits;

use App\Http\Controllers\Controller;
use App\Models\Permits\Permit;

class PermitController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $this->authorize('bitboss.permits.show');

        return view('bitboss.permits.index');
    }
}

app/Http/Controllers/Web/Bitboss/Reports/ReportController.php
<?php

namespace App\Http\Controllers\Web\Bitboss\Reports;

use App\Http\Controllers\Controller;
use App\Models\Permits\Permit;
use App\Models\Reports\Report;
use App\Models\User;

class ReportController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        $this->authorize('bitboss.reports.show');

        $reports = Report::all();
        $users = User::all();

        return view('bitboss.reports.create', compact('reports', 'users'));
    }
}

app/Http/Controllers/Web/Bitboss/Reports/UploadController.php
<?php

namespace App\Http\Controllers\Web\Bitboss\Reports;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class UploadController extends Controller
{
    public function upload(Request $request)
    {
        $files = $request->allFiles();
        $uploadedFiles = [];
        $directory = $request->directory;
        $tmpPath = storage_path('app/public/uploads');
        $path = 'uploads/';

        foreach ($files as $fieldName => $file) {
            $fileName = Str::slug($file->getClientOriginalName())."-".(uniqid()).".".$file->extension();
            $file->move($tmpPath, $fileName);
            $uploadedFiles[] = [
                'field_name' => $fieldName,
                'path' => $path,
                'name' => $fileName,
                'size' => $file->getSize(),
                'type' => $file->getClientMimeType(),
                'url' => asset('storage/uploads/' . $fileName)
            ];
        }

        return $uploadedFiles;


    }
}

resources/views/bitboss/reports/create.blade.php
@extends('bitboss.app', ['title'=>__("Segnalazioni")])

@section('content')

    <div class="mb-7">
        <div class="content container-fluid col-10">

            <div class="card mb-3 mb-lg-5">
                <!-- Body -->
                <div class="card-body">
                    <div class="row align-items-md-center gx-md-5">
                        <div class="col-md-auto mb-3 mb-md-0">
                            <div class="d-flex align-items-center">
                                <img class="avatar avatar-xxl avatar-4by3 mr-4" src="{{asset('images/bitboss/reports/5-stars.svg')}}" alt="Image Description">

                                <div class="d-block">
                                    <h4 class="display-2 text-dark mb-0">23</h4>
                                    <p><span class="badge badge-soft-dark badge-pill ml-1">+1 ultimo mese</span></p>
                                </div>
                            </div>
                        </div>

                        <div class="col-md">
                            <ul class="list-unstyled list-unstyled-py-2 mb-0">
                                <!-- Review Ratings -->
                                <li class="d-flex align-items-center font-size-sm">
                                    <span class="mr-3">5 stelle</span>
                                    <div class="progress flex-grow-1">
                                        <div class="progress-bar" role="progressbar" style="width: 82%;" aria-valuenow="82" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <span class="ml-3">4</span>
                                </li>
                                <!-- End Review Ratings -->

                                <!-- Review Ratings -->
                                <li class="d-flex align-items-center font-size-sm">
                                    <span class="mr-3">4 stelle</span>
                                    <div class="progress flex-grow-1">
                                        <div class="progress-bar" role="progressbar" style="width: 18%;" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <span class="ml-3">3</span>
                                </li>
                                <!-- End Review Ratings -->

                                <!-- Review Ratings -->
                                <li class="d-flex align-items-center font-size-sm">
                                    <span class="mr-3">3 stelle</span>
                                    <div class="progress flex-grow-1">
                                        <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <span class="ml-3">0</span>
                                </li>
                                <!-- End Review Ratings -->

                                <!-- Review Ratings -->
                                <li class="d-flex align-items-center font-size-sm">
                                    <span class="mr-3">2 stelle</span>
                                    <div class="progress flex-grow-1">
                                        <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <span class="ml-3">0</span>
                                </li>
                                <!-- End Review Ratings -->

                                <!-- Review Ratings -->
                                <li class="d-flex align-items-center font-size-sm">
                                    <span class="mr-3">1 stella</span>
                                    <div class="progress flex-grow-1">
                                        <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <span class="ml-3">0</span>
                                </li>
                                <!-- End Review Ratings -->
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Body -->
            </div>

            <reports :users-prop="{{$users}}" upload-url-prop="{{route('bitboss.upload')}}" csrf="{{csrf_token()}}" v-cloak></reports>
        </div>
    </div>

@endsection