routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', App\Http\Controllers\Auth\AuthRedirectorController::class);

Route::name('admin.')->prefix('admin')->middleware(['isAdmin', 'auth'])->group(function () {
    Route::get('/dashboard', \App\Http\Controllers\Web\Admin\DashboardController::class)->name('dashboard');

    /** Notifications */
        Route::get('/notifications/{notification}/read', '\App\Http\Controllers\Web\Admin\Notifications\NotificationController@read')->name('notifications.read');
        Route::get('/notifications/readAll', '\App\Http\Controllers\Web\Admin\Notifications\NotificationController@readAll')->name('notifications.readAll');

    /** Models */
        Route::resource('users', \App\Http\Controllers\Web\Admin\Users\UserController::class, ['except' => ['show']]);
        Route::resource('permits', \App\Http\Controllers\Web\Admin\Permits\PermitController::class, ['except' => ['show']]);
        Route::resource('reports', \App\Http\Controllers\Web\Admin\Reports\ReportController::class);
});

Route::name('bitboss.')->prefix('bitboss')->middleware(['isBitboss', 'auth'])->group(function () {
    Route::get('/home', \App\Http\Controllers\Web\Bitboss\HomeController::class)->name('home');

    /** Notifications */
        Route::get('/notifications/{notification}/read', '\App\Http\Controllers\Web\Bitboss\Notifications\NotificationController@read')->name('notifications.read');
        Route::get('/notifications/readAll', '\App\Http\Controllers\Web\Admin\Bitboss\NotificationController@readAll')->name('notifications.readAll');

    /** Models */
        Route::resource('permits', \App\Http\Controllers\Web\Bitboss\Permits\PermitController::class);
        Route::resource('reports', \App\Http\Controllers\Web\Bitboss\Reports\ReportController::class);

    /** Files */
        Route::post('uploads', '\App\Http\Controllers\Web\Bitboss\Reports\UploadController@upload')->name('upload');
});

resources/views/admin/partials/_errors_list.blade.php
@if($errors->any())
    <div class="alert alert-danger" role="alert">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/partials/_flash_messages.blade.php
@if (session()->has('message'))
    <div class="m-2">
        <div class="alert alert-success ">
            {{ session('message') }}
        </div>
    </div>
@endif

@if (session()->has('error'))
    <div class="m-2">
        <div class="alert alert-danger ">
            {{ session('error') }}
        </div>
    </div>
@endif

resources/views/admin/partials/sidebar.blade.php
<aside class="js-navbar-vertical-aside navbar navbar-vertical-aside navbar-vertical navbar-vertical-fixed navbar-expand-xl navbar-bordered default navbar-vertical-aside-initialized">
    <div class="navbar-vertical-container">
        <div class="navbar-vertical-footer-offset">
            <div class="navbar-brand-wrapper justify-content-between">
                <a class="navbar-brand" href="{{route('admin.dashboard')}}" aria-label="Front">
                    <img class="img-fluid" src="{{asset('images/logo/logo.png')}}" alt="Logo">
                    <img class="navbar-brand-logo-mini" src="../assets/svg/logos/logo-short.svg" alt="Logo">
                </a>
            </div>

            <!-- Content -->
            <div class="navbar-vertical-content mt-4">
                <ul class="navbar-nav navbar-nav-lg nav-tabs">
                    <li class="navbar-vertical-aside-has-menu">
                        <a class="js-navbar-vertical-aside-menu-link nav-link" href="{{route('admin.dashboard')}}" title="Dashboards">
                            <i class="tio-home nav-icon"></i>
                            <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate spinner-on-click">Dashboard</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <small class="nav-subtitle" title="Layouts">Team</small>
                        <small class="tio-more-horizontal nav-subtitle-replacer"></small>
                    </li>

                    <li class="navbar-vertical-aside-has-menu">
                        <a class="js-navbar-vertical-aside-menu-link nav-link" href="{{route('admin.permits.index')}}" title="Permessi">
                            <i class="tio-event nav-icon"></i>
                            <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate spinner-on-click">Permessi</span>
                        </a>
                    </li>

                    <li class="navbar-vertical-aside-has-menu">
                        <a class="js-navbar-vertical-aside-menu-link nav-link" href="{{route('admin.reports.index')}}" title="Reports">
                            <i class="tio-report nav-icon"></i>
                            <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate spinner-on-click">Segnalazioni</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <small class="nav-subtitle" title="Layouts">Bitboss Ticket</small>
                        <small class="tio-more-horizontal nav-subtitle-replacer"></small>
                    </li>

                    <li class="navbar-vertical-aside-has-menu">
                        <a class="js-navbar-vertical-aside-menu-link nav-link" href="#" title="Ticket">
                            <i class="tio-headphones nav-icon"></i>
                            <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate spinner-on-click">Ticket</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <small class="nav-subtitle" title="Layouts">Amministrazione</small>
                        <small class="tio-more-horizontal nav-subtitle-replacer"></small>
                    </li>

                    <li class="navbar-vertical-aside-has-menu">
                        <a class="js-navbar-vertical-aside-menu-link nav-link" href="{{route('admin.users.index')}}" title="Utenti">
                            <i class="tio-user nav-icon"></i>
                            <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate spinner-on-click">Utenti</span>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- End Content -->
        </div>
    </div>
</aside>